spring.application.name=auth-service
server.port=8081
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmase
spring.datasource.username=postgres
spring.datasource.password=${JDBC_PASSWORD:change_me}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


jwt.secret=${JWT_SECRET:change_me}

jwt.expiration=86400000

# Logging Configuration
logging.level.root=INFO
logging.level.com.soumen.MedicalAI=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


spring.security.oauth2.client.registration.google-user.provider=google
spring.security.oauth2.client.registration.google-user.client-id=${GOOGLE_USER_CLIENT_ID:change_me.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google-user.client-secret=${GOOGLE_USER_CLIENT_SECRET:change_me}
spring.security.oauth2.client.registration.google-user.scope=profile,email

spring.security.oauth2.client.registration.google-pharm.scope=profile,email
spring.security.oauth2.client.registration.google-pharm.provider=google
spring.security.oauth2.client.registration.google-pharm.client-id=${GOOGLE_PHARM_CLIENT_ID:change_me.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google-pharm.client-secret=${GOOGLE_PHARM_CLIENT_SECRET:change_me}

#spring.datasource.url=${JDBC_URL}
#spring.datasource.username=postgres
#spring.datasource.password=${JDBC_PASSWORD:change_me}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#
#
#jwt.secret=${JWT_SECRET:change_me}
#
#jwt.expiration=${JWT_EXPIRATION}
#
## Logging Configuration
#logging.level.root=INFO
#logging.level.com.soumen.MedicalAI=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
#
## OAuth2
#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

