spring.application.name=notification-service


server.port=8085

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmase
spring.datasource.username=postgres
spring.datasource.password=${JDBC_PASSWORD:change_me}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
