spring.application.name=reservation-service

server.port = 8086

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=${JWT_SECRET:change_me}

jwt.expiration=86400000


# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmase
spring.datasource.username=postgres
spring.datasource.password=${JDBC_PASSWORD:change_me}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Logging Configuration
logging.level.root=INFO
logging.level.com.soumen.MedicalAI=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

