spring.application.name=inventory-service

server.port = 8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=k9Xv2mQpL7nRjYwZdA3sBtHuEcFgNiOx+Wq1VyK8Ml0=

jwt.expiration=86400000

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmase
spring.datasource.username=postgres
spring.datasource.password=database2025
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Logging Configuration
logging.level.root=INFO
logging.level.com.soumen.MedicalAI=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


